FROM python:3.12-slim
COPY calculator.py /
COPY requirements.txt .
COPY calculator_helper.py /
COPY calculator_rest_service.py /
COPY models.py /
RUN pip install -r requirements.txt
ENTRYPOINT [ "python" , "calculator.py" ]