name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r BE/requirements.txt
          pip install pytest requests

      - name: Start REST API
        run: |
          python BE/calculator.py --rest &
        shell: bash

      - name: Run tests with pytest
        run: pytest --junit-xml=report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: report.xml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.USERNAME_SECRET }}
          password: ${{ secrets.PASSWORD_SECRET }}
          registry: judevops.azurecr.io

      - name: Build Docker image
        run: docker build -t judevops.azurecr.io/albin_cederlof_calc:latest BE/

      - name: Push Docker image
        run: docker push judevops.azurecr.io/albin_cederlof_calc:latest
